/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.BiddingPlatform.AdvertisingStrategy;
import Business.CustomerUsageHistory.CustomerUsage;
import Business.CustomerUsageHistory.CustomerUsageHistory;
import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Network.Network;
import Business.Purchase.AdvertiserOrder;
import Business.UserAccount.UserAccount;
import Ecosystem.AdvertiserProduct;
import Ecosystem.Customer;
import Ecosystem.EcoSystem;
import Ecosystem.PublisherContent;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author prat
 */
public class DisplayPublisherContent extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private AdvertiserEnterprise ae;
    private Enterprise e;
    private UserAccount ua;
    private String s;
    private AdvertisingStrategy a;
    private String ADPATH = "/UserInterface/CustomerRole/honda.jpg";

    /**
     * Creates new form DisplayPublisherContent
     */
    public DisplayPublisherContent(JPanel upc, EcoSystem system, AdvertiserEnterprise ae, Enterprise e, UserAccount ua, String s, AdvertisingStrategy as, String adPath) {
        initComponents();
        this.userProcessContainer = upc;
        this.ae = ae;
        this.ua = ua;
        this.system = system;
        this.s = s;
        this.e = e;
        this.a = as;
        if (adPath != null) {
            this.ADPATH = adPath;
        }
        populatePublisherContent();
        populateAdSpace();

        clickJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(ADPATH)));

    }

    private void populateAdSpace() {
        if (e instanceof AdvertiserEnterprise) {
            AdvertiserEnterprise ae = (AdvertiserEnterprise) e;
            for (AdvertisingStrategy as : ae.getAdvertisingStrategyDirectory().getAdvertisingStrategyList()) {
                if (as.getCategoryList().equals(s)) {
                    for (AdvertiserProduct ap : ae.getAdProList()) {
                        this.ADPATH = ap.getFILENAME();
                    }
                }
            }

        }
    }

    private void populatePublisherContent() {
        Customer c = (Customer) ua.getEmployee();
        if (e instanceof PublisherEnterprise) {
            for (PublisherContent pc : e.getProductCatalog().getProductList()) {
                for (String cat : pc.getCategoryList()) {
                    if (c.getInterestList().contains(s) && s.equals(cat)) {
                        String title = pc.getProdName();
                        titleJtext.setText(title);
                        String desc = pc.getContentDescription();
                        descJtextField.setText(desc);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titleJtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        descJtextField = new javax.swing.JTextField();
        backjButton1 = new javax.swing.JButton();
        clickJButton = new javax.swing.JButton();
        AdvertiserContent = new javax.swing.JLabel();

        jLabel1.setText("Content title:");

        jLabel2.setText("Description:");

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        clickJButton.setText("Click!");
        clickJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickJButtonActionPerformed(evt);
            }
        });

        AdvertiserContent.setText("AdvertiserContent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clickJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdvertiserContent)
                        .addGap(61, 61, 61)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(titleJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(descJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(clickJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdvertiserContent)
                .addGap(63, 63, 63)
                .addComponent(backjButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void clickJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickJButtonActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getEmployee();
        CustomerUsage cu = c.getCustomerUsageHistory().addCustomerUsage();
        //AdvertiserProduct ap = null;
        AdvertiserOrder ao = new AdvertiserOrder();
        int i = cu.getClick();
        cu.setClick(i + 1);
        for (AdvertiserProduct ap : ae.getAdProList()) {

            ae.getMasterAdvertiserOrderCatalog().addOrder(ao);
            System.out.println("In order");
//                float value = a.getCostPerClick();

            ao.setAdvertiserProduct(ap);
            //             ao.setOrderAmount(value);

            int j = ap.getNo_of_views();
            ap.setNo_of_views(j + 1);

            cu.setPublisherContent(ap);
            cu.setAdvertiserProduct(ap);
            System.out.println(ap);

        }

        ProductPurchaseJPanel pp = new ProductPurchaseJPanel(userProcessContainer, system, ae, ua);

        userProcessContainer.add(
                "ProductPurchaseJPanel", pp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();

        layout.next(userProcessContainer);

    }//GEN-LAST:event_clickJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdvertiserContent;
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton clickJButton;
    private javax.swing.JTextField descJtextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField titleJtext;
    // End of variables declaration//GEN-END:variables
}
