/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PublisherProductManagerRole;

import Business.Enterprise.PublisherEnterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author prat
 */
public class PublisherProductManagerWorkArea extends javax.swing.JPanel {
private JPanel userProcessContainer;
private PublisherEnterprise publisherEnterprise;

    /**
     * Creates new form PublisherProductManagerWorkArea
     */
    public PublisherProductManagerWorkArea(JPanel userProcessContainer,PublisherEnterprise publisherEnterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.publisherEnterprise=publisherEnterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addContentJButton = new javax.swing.JButton();
        viewAddedProducts = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addContentJButton.setText("Add Content");
        addContentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContentJButtonActionPerformed(evt);
            }
        });

        viewAddedProducts.setText("View added products");
        viewAddedProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddedProductsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Publisher Product Manager Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(addContentJButton))
                            .addComponent(viewAddedProducts)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(addContentJButton)
                .addGap(33, 33, 33)
                .addComponent(viewAddedProducts)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addContentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContentJButtonActionPerformed
        // TODO add your handling code here:
        AddContentWorkArea ac=new AddContentWorkArea(userProcessContainer,publisherEnterprise);
        userProcessContainer.add("AddContentWorkArea", ac);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addContentJButtonActionPerformed

    private void viewAddedProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddedProductsActionPerformed
        // TODO add your handling code here:
        ViewAddedContentJPanel vc=new ViewAddedContentJPanel(userProcessContainer,publisherEnterprise);
        userProcessContainer.add("ViewAddedContentJPanel", vc);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAddedProductsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContentJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewAddedProducts;
    // End of variables declaration//GEN-END:variables
}
