/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MarketingAgencyManagerRole;

import Business.BiddingPlatform.MarketingStrategy;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Ecosystem.AdExchange;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prat
 */
public class AddMarketingStrategyJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;

    /**
     * Creates new form AddPublisherStrategyJPanel
     */
    public AddMarketingStrategyJPanel(JPanel upc, Enterprise e) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = e;
        categoryJComboBox.removeAllItems();
        categoryJComboBox.addItem("Movies");
        categoryJComboBox.addItem("Sports");
        categoryJComboBox.addItem("Cars");
        categoryJComboBox.addItem("Books");
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLocJText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        userAgeJText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        timeJtext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categoryJComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addStrategyJButton = new javax.swing.JButton();
        costPerClickJText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();

        jLabel1.setText("Add Strategies");

        jLabel2.setText("Cost per impression:");

        jLabel4.setText("User Location:");

        categoryJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("User age:");

        jLabel7.setText("Category: ");

        jLabel8.setText("Time of day:");

        addStrategyJButton.setText("Add Strategy");
        addStrategyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStrategyJButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("For e.g.:Morning, afternoon, evening, night");

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(addStrategyJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(userAgeJText, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userLocJText, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(costPerClickJText))
                                        .addGap(263, 263, 263))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(categoryJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(117, 117, 117))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(timeJtext)
                                                .addGap(51, 51, 51)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(17, 17, 17)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(costPerClickJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userLocJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userAgeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(categoryJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStrategyJButton)
                    .addComponent(backjButton1))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addStrategyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStrategyJButtonActionPerformed
        // TODO add your handling code here:

        float costPerImpression = Float.parseFloat(costPerClickJText.getText());

        String userLocation = userLocJText.getText();
        int userAge = Integer.parseInt(userAgeJText.getText());
        
        String cat = (String) categoryJComboBox.getSelectedItem();
        String timeOfDay = timeJtext.getText();

        PublisherEnterprise pubEnt = (PublisherEnterprise)enterprise;
        MarketingStrategy as = pubEnt.getMarketingStrategyList().addMarketingStrategy();
        
        as.addCategory(cat);
        System.out.println(cat);
        
        as.setCostPerImpression(costPerImpression);
        System.out.println(costPerImpression);
        as.setUserAge(userAge);
        System.out.println(userAge);
        as.setUserLocation(userLocation);
        System.out.println(userLocation);
        as.setTimeOfDay(timeOfDay);
        System.out.println(timeOfDay);
        as.setPublisherName(pubEnt.getName());
        System.out.println(pubEnt.getName());
        System.out.println(cat);
        JOptionPane.showMessageDialog(null, "Strategy added successfully");
    }//GEN-LAST:event_addStrategyJButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStrategyJButton;
    private javax.swing.JButton backjButton1;
    private javax.swing.JComboBox categoryJComboBox;
    private javax.swing.JTextField costPerClickJText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField timeJtext;
    private javax.swing.JTextField userAgeJText;
    private javax.swing.JTextField userLocJText;
    // End of variables declaration//GEN-END:variables
}
