/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminRole;

import Ecosystem.AdExchange;
import Ecosystem.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author varsha
 */
public class ManageAdExchangeJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form ManageAdExchangeJPanel
     */
    public ManageAdExchangeJPanel(JPanel upc,EcoSystem system) {
        initComponents();
        this.userProcessContainer=upc;
        this.system=system;
        populateAdExchangeTable();
    }
    
    private void populateAdExchangeTable() {
        DefaultTableModel dtm= (DefaultTableModel) adexchangeTable.getModel();
        dtm.setRowCount(0);
        for(AdExchange ae:system.getAdExchangeList().getAdExchangeList()){
            Object row[]=new Object[1];
            row[0]=ae;
            dtm.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        creatAdExchangeJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adexchangeTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        adexchangeNameJtextField = new javax.swing.JTextField();
        createUserAccountJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Ad Exchange");

        creatAdExchangeJButton.setText("Create Ad Exchange");
        creatAdExchangeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatAdExchangeJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        adexchangeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "AdExchange Name"
            }
        ));
        jScrollPane1.setViewportView(adexchangeTable);

        jLabel3.setText("Name");

        createUserAccountJButton.setText("Create User Account");
        createUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserAccountJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(18, 18, 18)
                                .addComponent(creatAdExchangeJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(createUserAccountJButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel3)
                        .addGap(66, 66, 66)
                        .addComponent(adexchangeNameJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adexchangeNameJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(createUserAccountJButton)
                    .addComponent(creatAdExchangeJButton))
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void creatAdExchangeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatAdExchangeJButtonActionPerformed
        // TODO add your handling code here:
        String name=adexchangeNameJtextField.getText();
        if(name.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid ad exchange name");
            return;
        }
        for(AdExchange ae:system.getAdExchangeList().getAdExchangeList()) {
            if(ae.getName().equals(name)) {
                JOptionPane.showMessageDialog(null, "AdExchange already exists");
                return;
            }
        }
        AdExchange adExchange=system.getAdExchangeList().addAdExchange(name);
        System.out.println(name);
        populateAdExchangeTable();
        
    }//GEN-LAST:event_creatAdExchangeJButtonActionPerformed

    private void createUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserAccountJButtonActionPerformed
        // TODO add your handling code here:
        for(AdExchange ae:system.getAdExchangeList().getAdExchangeList()) {
            if(ae.getName().equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter a valid ad exchange name");
                return;
            }
        }
        int row=adexchangeTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select atleast one row.", "Warning!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        AdExchange ae = (AdExchange)adexchangeTable.getValueAt(row, 0);
        if(row>=0) {
        ManageAdExchangeUserAccount maeu=new ManageAdExchangeUserAccount(userProcessContainer,system,ae);
        userProcessContainer.add("ManageAdExchangeUserAccount", maeu);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        
        
    }//GEN-LAST:event_createUserAccountJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adexchangeNameJtextField;
    private javax.swing.JTable adexchangeTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton creatAdExchangeJButton;
    private javax.swing.JButton createUserAccountJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
