/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminRole;

import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Ecosystem.AdExchange;
import Ecosystem.EcoSystem;
import UserInterface.DummyJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author varsha
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private AdExchange adExchange;
    String AD_PATH = "/UserInterface/SystemAdminRole/download (1).jpg";

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel upc, EcoSystem system,AdExchange ae) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        this.adExchange=ae;
        if(adExchange!=null) {
            pubEntJButton.setEnabled(true);
            advEntJButton.setEnabled(true);
        }
        else{
            pubEntJButton.setEnabled(true);
            advEntJButton.setEnabled(true);
        }
        populateTree();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void populateTree() {
        DefaultTreeModel dtm = (DefaultTreeModel) jTree1.getModel();

        ArrayList<Network> networkList = system.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;

        Network network;
        Enterprise enterprise;
        Organization organization;

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) dtm.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        //populating networks

        for (int i = 0; i < networkList.size(); i++) {
            network = networkList.get(i);
            networkNode = new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);

            //creating enterprise
            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            for (int j = 0; j < enterpriseList.size(); j++) {
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);

                //creating organizations
                organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                for (int k = 0; k < organizationList.size(); k++) {
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }
        dtm.reload();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        manageNetworkJButton = new javax.swing.JButton();
        jButtonEnterprise = new javax.swing.JButton();
        jButtonEnterpriseAdmin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        manageAdExchangeJButton = new javax.swing.JButton();
        pubEntJButton = new javax.swing.JButton();
        advEntJButton = new javax.swing.JButton();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        manageNetworkJButton.setText("Manage Networks");
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });

        jButtonEnterprise.setText("Manage Enterprise");
        jButtonEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterpriseActionPerformed(evt);
            }
        });

        jButtonEnterpriseAdmin.setText("Enterprise Admin");
        jButtonEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterpriseAdminActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        manageAdExchangeJButton.setText("Manage AdExchange");
        manageAdExchangeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdExchangeJButtonActionPerformed(evt);
            }
        });

        pubEntJButton.setText("Publisher Enterprise");
        pubEntJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubEntJButtonActionPerformed(evt);
            }
        });

        advEntJButton.setText("Advertiser Enterprise");
        advEntJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advEntJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageNetworkJButton)
                            .addComponent(manageAdExchangeJButton)
                            .addComponent(jButtonEnterprise)
                            .addComponent(jButtonEnterpriseAdmin)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(pubEntJButton)
                        .addGap(48, 48, 48)
                        .addComponent(advEntJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(manageAdExchangeJButton)
                        .addGap(18, 18, 18)
                        .addComponent(manageNetworkJButton)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonEnterprise)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonEnterpriseAdmin)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pubEntJButton)
                            .addComponent(advEntJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(476, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel mnjp = new ManageNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageNetworkJPanel", mnjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void jButtonEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterpriseActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel mejp = new ManageEnterpriseJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageEnterpriseJPanel", mejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_jButtonEnterpriseActionPerformed

    private void jButtonEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterpriseAdminActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel meajp = new ManageEnterpriseAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageEnterpriseJPanel", meajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonEnterpriseAdminActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        populateTree();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageAdExchangeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdExchangeJButtonActionPerformed
        // TODO add your handling code here:
        ManageAdExchangeJPanel ma = new ManageAdExchangeJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageEnterpriseJPanel", ma);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageAdExchangeJButtonActionPerformed

    private void pubEntJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubEntJButtonActionPerformed
        // TODO add your handling code here:
        for(AdExchange ae:system.getAdExchangeList().getAdExchangeList()) {
            for(Enterprise e:ae.getPublisherEnterpriseList()) {
            PublisherEnterprise ent=(PublisherEnterprise)e;
            ae.addPublisherEnterprise(ent);
            }
        }
    }//GEN-LAST:event_pubEntJButtonActionPerformed

    private void advEntJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advEntJButtonActionPerformed
        // TODO add your handling code here:
        for(AdExchange ae:system.getAdExchangeList().getAdExchangeList()) {
            for(Enterprise e:ae.getAdvertiserEnterpriseList()) {
            AdvertiserEnterprise ent=(AdvertiserEnterprise)e;
            ae.addAdvertiserEnterprise(ent);
            }
        }
    }//GEN-LAST:event_advEntJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advEntJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEnterprise;
    private javax.swing.JButton jButtonEnterpriseAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton manageAdExchangeJButton;
    private javax.swing.JButton manageNetworkJButton;
    private javax.swing.JButton pubEntJButton;
    // End of variables declaration//GEN-END:variables
}
