/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FinanceManagerRole;

import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Purchase.AdvertiserOrder;
import Business.Purchase.MasterAdvertiserOrderCatalog;
import Business.WorkQueue.PublisherFinanceWorkRequest;
import Business.WorkQueue.WorkRequest;
import Ecosystem.EcoSystem;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author varsha
 */
public class PublisherFinanceRequestsWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form FinanceManagerWorkArea
     */
    public PublisherFinanceRequestsWorkArea(JPanel upc, EcoSystem system) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        populateRequestTable();
    }

    private void populateRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) financeRequestJTable.getModel();
        dtm.setRowCount(0);
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                    for (WorkRequest request : org.getWorkQueue().getWorkRequestList()) {
                        Object row[] = new Object[4];
                        row[0] = request.getSender();
                        row[1] = request.getReceiver();
                        if (e instanceof AdvertiserEnterprise) {
                            AdvertiserEnterprise ae = (AdvertiserEnterprise) e;
                            for (AdvertiserOrder ao : ae.getMasterAdvertiserOrderCatalog().getMasterOrderList()) {
                                row[2] = ao.getOrderAmount();
                            }
                            row[3] = request.getMessage();
                            dtm.addRow(row);
                        }
                    }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        approveJButton = new javax.swing.JButton();
        declineJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        financeRequestJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Payment requests");

        approveJButton.setText("Approve request");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });

        declineJButton.setText("Decline request");
        declineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineJButtonActionPerformed(evt);
            }
        });

        financeRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Payment", "Status"
            }
        ));
        jScrollPane1.setViewportView(financeRequestJTable);

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshJButton)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(approveJButton)
                        .addGap(142, 142, 142)
                        .addComponent(declineJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(refreshJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveJButton)
                    .addComponent(declineJButton))
                .addGap(184, 184, 184))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = financeRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        PublisherFinanceWorkRequest request = (PublisherFinanceWorkRequest) financeRequestJTable.getValueAt(selectedRow, 0);

        request.setStatus("Processing");
        request.setMessage("Approved");

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof AdvertiserEnterprise) {
                    AdvertiserEnterprise ae = (AdvertiserEnterprise) e;
                    for (AdvertiserOrder ao : ae.getMasterAdvertiserOrderCatalog().getMasterOrderList()) {
                        ao.getPayment().setStatus("Approved");                
                        populateRequestTable();
                    }
                }
            }
        }


    }//GEN-LAST:event_approveJButtonActionPerformed

    private void declineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = financeRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }

        PublisherFinanceWorkRequest request = (PublisherFinanceWorkRequest) financeRequestJTable.getValueAt(selectedRow, 0);

        request.setRequestStatus("Declined");
        request.setMessage("Declined");

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof AdvertiserEnterprise) {
                    AdvertiserEnterprise ae = (AdvertiserEnterprise) e;
                    for (AdvertiserOrder ao : ae.getMasterAdvertiserOrderCatalog().getMasterOrderList()) {
                        ao.getPayment().setStatus("Declined");
                        populateRequestTable();
                    }
                }
            }
        }
    }//GEN-LAST:event_declineJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed

        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveJButton;
    private javax.swing.JButton declineJButton;
    private javax.swing.JTable financeRequestJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
